### ISSUE TITLE
Type requirement and optionality

### ISSUE THREAD

**Issue by thanpolas** [mschema/mschema#4]
Would you consider enriching the type definition with hints as to wether they are required or optional?

I am strongly influenced by [Closure's Annotation paradigm](https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en) thus my examples are a direct copy from there...

#### A nullable string

Describes a String type that can also have a null value. Good for explicitly initializing all values using `null` and optionally assigning a *String* value to them.

```json
{
  "type": "?string"
}
```

#### An optional string

Describes a String type that may or may not be defined.

```json
{
  "type": "string="
}
```

**Comment by Marak** [comment]
At this time, I don't want to mix annotations in with data.

It will complicate the parser and other tools which need to parse mschema.

If you need to add an annotation system, I would recommend building a separate module which performs a search and replace for annotations before the schema is called by mschema's validate method.
